note: 'train'
# configs of data

model: 'deeplab'
train: True
multigpu: False
fixbn: True
fix_seed: True

# Optimizaers
learning_rate: 7.5e-5
num_steps: 5000
epochs: 20
weight_decay: 0.0005
momentum: 0.9
power: 0.9
round: 6

# Logging
print_freq: 1
save_freq: 2000
tensorboard: False
neptune: False
screen: False
val: True
val_freq: 300

# Dataset
source: 'gta5'
target: 'cityscapes'
worker: 4
batch_size: 4 #2

#Transforms
input_src: 720
input_tgt: 720
crop_src: 600
crop_tgt: 600
mirror: True
scale_min: 0.5
scale_max: 1.5
rec: False

# Model hypers
init_weight: '/share_chairilg/weights/DeepLab_resnet_pretrained_init_dass.pth'
restore_from: None

snapshot: './results/source_only_half/snapshot/'
result: './results/source_only_half/miou_result/'
log: './results/source_only_half/log/'
plabel: './plabel'
gta5: {
        data_dir: '/share_chairilg/data/gta5',
        data_list: './dataset/list/gta5_list.txt',
        input_size: [1280, 720]
        }
synthia: {
        data_dir: '/dataset/SYNTHIA/',
        data_list: './dataset/list/synthia_list.txt',
        input_size: [1280, 760]
        }
cityscapes: {
        data_dir: '/share_chairilg/data/cityscapes/uda_variant',
        data_list: './dataset/list/cityscapes_train.txt',
        input_size: [1024, 512]
        }
